/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
              "surface": "#0e0e13",
              "surface-tint": "#d593ff",
              "outline-variant": "#48474d",
              "on-secondary": "#330059",
              "on-error-container": "#ffb2b9",
              "on-background": "#f9f5fd",
              "surface-variant": "#25252d",
              "on-secondary-fixed-variant": "#741fb7",
              "on-tertiary-fixed-variant": "#006632",
              "on-secondary-fixed": "#500087",
              "on-secondary-container": "#e5c3ff",
              "secondary": "#c37fff",
              "primary-fixed": "#cc7fff",
              "on-tertiary-container": "#005b2c",
              "primary-fixed-dim": "#c36aff",
              "secondary-container": "#690bac",
              "on-tertiary-fixed": "#004621",
              "on-surface-variant": "#acaab1",
              "primary-container": "#cc7fff",
              "tertiary-fixed": "#00fd87",
              "surface-container-low": "#131319",
              "background": "#0e0e13",
              "primary-dim": "#ca7bff",
              "error-dim": "#d73357",
              "on-primary": "#4b0075",
              "primary": "#d593ff",
              "tertiary-dim": "#00ed7e",
              "surface-container-highest": "#25252d",
              "surface-bright": "#2c2b33",
              "on-primary-container": "#3a005b",
              "on-error": "#490013",
              "surface-container": "#19191f",
              "error": "#ff6e84",
              "on-primary-fixed": "#000000",
              "surface-container-lowest": "#000000",
              "on-primary-fixed-variant": "#480070",
              "secondary-fixed": "#e6c5ff",
              "secondary-dim": "#c37fff",
              "inverse-on-surface": "#55545b",
              "inverse-primary": "#8d26cc",
              "inverse-surface": "#fcf8ff",
              "tertiary": "#a4ffb9",
              "error-container": "#a70138",
              "surface-container-high": "#1f1f26",
              "secondary-fixed-dim": "#ddb3ff",
              "surface-dim": "#0e0e13",
              "tertiary-container": "#00fd87",
              "outline": "#76747b",
              "tertiary-fixed-dim": "#00ed7e",
              "on-tertiary": "#006532",
              "on-surface": "#f9f5fd",
              "deal-green": "#00FF88"
            },
            fontFamily: {
              "headline": ["Space Grotesk", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"],
              "orbitron": ["Orbitron", "sans-serif"],
              "barlow": ["Barlow Condensed", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
